name: flutterphone
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core : ^0.5.0
  contact_picker: ^0.0.2
  #firebase_storage:
  photo_view: ^0.4.2
  firebase_auth:
  #firebase_auth: ^0.13.0
  shared_preferences: ^0.5.6+3
  random_string: ^2.0.1
  cloud_firestore: ^0.14.0
  pinput: ^0.2.6
  flutter_svg: ^0.19.1
  http: ^0.12.0+2
  circular_check_box: ^1.0.4
  custom_radio: ^0.1.2
  pin_code_text_field: ^1.7.1
  pin_entry_text_field: ^0.1.4
  image_picker: ^0.6.7+22
  fluttertoast: ^3.1.3
  email_validator: ^1.0.0
  path_provider: ^1.6.27
  url_launcher:
  location: ^3.0.0
  firebase_cloud_messaging: ^4.0.4+1
  flutter_rating_bar: ^3.2.0+1
  carousel_slider: ^3.0.0
  shimmer: ^1.1.2
  hexagon: ^0.1.0
  table_calendar: ^2.2.3
  rate_my_app: ^0.4.0
  curved_navigation_bar: ^0.3.7 #latest version
  lite_rolling_switch: ^0.1.1
  font_awesome_flutter:
  stacked: ^1.9.5
  wave: ^0.1.0
  flutter_custom_clippers: ^1.1.2
  bottom_navy_bar: ^5.6.0
  google_nav_bar: ^5.0.3
  carousel_pro: ^1.0.0
  toast: ^0.1.5
  fdottedline: ^1.0.1
  date_range_picker: ^1.0.7
  google_maps_flutter: ^1.0.3
  geolocator: ^6.1.1
  time_range_picker: ^2.0.1
  time_picker_widget: ^1.0.0+9
  percent_indicator: "^2.1.5"
  flutter_local_notifications: ^1.4.4+1
  rxdart: ^0.24.1
  clippy_flutter: ^1.1.1
  flutter_slidable: ^0.5.7
    #google_maps_flutter:
   #location: ^3.0.0
  #geolocator: ^2.1.0
  #flutter_plugin_android_lifecycle: ^1.0.0
  #location_platform_interface: ^1.0.0









dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/work/
    - assets/icons/x.png
    - assets/icons/y.png
    - assets/work/house-reforms.png
    - assets/work/taqaat.png
    - assets/work/ho.jpg
    - assets/work/back.jpg
    - assets/work/cv.jpg
    - assets/icons/worker.png
    - assets/icons/current.png
    - assets/work/bal.png
    - assets/work/sabak.png
    - assets/work/najar.png
    - assets/work/ele.png
    - assets/work/dahan.png
    - assets/work/intro1.jpg
    - assets/work/intro2.jpg
    - assets/work/intro3.jpg
    - assets/work/intro4.jpg
    - assets/work/choice.jpg
    - assets/icons/watsapp.jpg
    - assets/work/ch.jpg
    - assets/work/ch.png
    - assets/work/w1.jpg
    - assets/work/w2.jpg
    - assets/work/najar.png
    - assets/work/w3.jpg
    - assets/work/w4.jpg
    - assets/work/dayoff.png
    - assets/work/cvtop.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: YuseiMagic
      fonts:
        - asset: fonts/YuseiMagic-Regular.ttf

    - family: Cairo-SemiBold
      fonts:
        - asset: fonts/Cairo-SemiBold.ttf

    - family: Changa
      fonts:
        - asset: fonts/Changa.ttf

    - family: Lemonada
      fonts:
        - asset: fonts/Lemonada-Medium.ttf

    - family: vibes
      fonts:
        - asset: fonts/Vibes-Regular.ttf

    - family: moza
      fonts:
          - asset: fonts/Maoza-Regular.ttf

  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
